### ISSUE TITLE
`retry(seconds=...)` broke

### ISSUE THREAD

**Issue by tony** [tmux-python/libtmux#368]
Instead

```
import time
t = time.process_time()

while (time.process_time() - t) * 1000 < 2:
    # stuff happens
    time.sleep(0.1)
```

Find cross platform way to do timeout with signals

See also https://github.com/tmux-python/tmuxp/issues/620

**Comment by categulario** [comment]
It turns out that this is the cause of https://github.com/tmux-python/tmuxp/issues/704#issuecomment-1128288348 . The current implementation of the `retry()` function is equivalent to `return True`.

Why is this function necessary? Maybe it can be replaced by a `sleep(some_millis)` in most cases. Seems strange needing to retry a block of code thousands of times until a condition meets. That makes me think (and taking a look at the places where it is used) that it can actually be accurately replaced by a `while` loop with the condition that breaks (which in fact would be equivalent since current implementation is a `return True`).

**Comment by categulario** [comment]
Ok, I just found a case where a piece of code was tried 89 times before it succeeded, which was about 300 ms.

**Comment by categulario** [comment]
I came up with this function:

```python
def retry(fun, secs=1):
    ini = time.time()

    while not fun():
        end = time.time()
        if end - ini >= secs:
            raise Exception('retry timed out')
```

which does the retrying thing accurately with the timeout, it is more or less clean to use (little change to the code) and reports when the retrying timed out:

```python
    def f():
        session.server._update_windows()
        return w.name == "sh"

    retry(f)

    assert w.name == "sh"
```

what do you think?

**Comment by categulario** [comment]
For an instant I thought this issue was about the `libtmux.test` function only, which is used exactly 10 times in testing code.

I understand that its usage can be extended to `tmuxp` code for cases like https://github.com/tmux-python/tmuxp/issues/96 and that probably motivates this code. However I see a few shortcomings:

* If it is available only as a mixin then using it requires using it from the class that implements the mixin. It might be that implementing it in Window and Pane is enough, it might be not. To me seems restrictive for no good reason and if it ever needs to be used when no window or pane is available then it leads its users to doing some weird tricks to have the function. Function that can very easily be just a function attached to nothing. 
* I think the calculation of time spent should be done with the `time` module, just because operations (like calling the callback) take time, so for the sake of unnecessary precision I would just call `time()` as in my proposal.
* I think the function should rise by default, and be explicitly silenced. A condition that didn't meet after the given time is probably an error anyways. Knowing the reason of the error by default seems reasonable.
* the while loop never enters, but that's probably a typo.

Things that I like:

* the `WaitTimeout` error
* the check for callable argument
* sleeping a small interval between calls, although it should probably be around `.1` second or less to have a more "real-time" effect. Waiting for 250 ms and failing to meet the condition implies the user waiting for half a second, which starts to feel like lag.

**Comment by tony** [comment]
@categulario Would you like to make a new PR with a wait function w/o the time function, using the `time` module?

if not i can get around to it in this weekend or next weekend

i may not be around in the weekdays as much due to normal work deadlines

**Comment by categulario** [comment]
> @categulario Would you like to make a new PR with a wait function w/o the time function, using the time module?

I didn't understand that.

**Comment by tony** [comment]
@categulario I edited it. I'm just asking if you want to make PR with an example of what you meant [here](https://github.com/tmux-python/libtmux/issues/368#issuecomment-1129427034)

**Comment by categulario** [comment]
Just updated #372 with that
